/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace StdInvariant {
  export type FuzzSelectorStruct = { addr: string; selectors: BytesLike[] };

  export type FuzzSelectorStructOutput = [string, string[]] & {
    addr: string;
    selectors: string[];
  };
}

export interface UnfollowMetaTxTestInterface extends utils.Interface {
  functions: {
    "IS_SCRIPT()": FunctionFragment;
    "IS_TEST()": FunctionFragment;
    "excludeArtifacts()": FunctionFragment;
    "excludeContracts()": FunctionFragment;
    "excludeSenders()": FunctionFragment;
    "failed()": FunctionFragment;
    "keyExists(string,string)": FunctionFragment;
    "setUp()": FunctionFragment;
    "targetArtifactSelectors()": FunctionFragment;
    "targetArtifacts()": FunctionFragment;
    "targetContracts()": FunctionFragment;
    "targetSelectors()": FunctionFragment;
    "targetSenders()": FunctionFragment;
    "testArrayHelpers()": FunctionFragment;
    "testBaseTest()": FunctionFragment;
    "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId()": FunctionFragment;
    "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name()": FunctionFragment;
    "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber()": FunctionFragment;
    "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract()": FunctionFragment;
    "testCannotExecuteMetaTx_WhenSignature_HasExpired()": FunctionFragment;
    "testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid()": FunctionFragment;
    "testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented()": FunctionFragment;
    "testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid()": FunctionFragment;
    "testCannotUnfollowIfNotFollowingTheTargetProfile()": FunctionFragment;
    "testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor(uint256)": FunctionFragment;
    "testCannotUnfollowIfPaused()": FunctionFragment;
    "testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist(uint256)": FunctionFragment;
    "testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore()": FunctionFragment;
    "testCannotUnfollowIfUnfollowerProfileDoesNotExist()": FunctionFragment;
    "testContractAddressesLoaderDeployer()": FunctionFragment;
    "testForkManagement()": FunctionFragment;
    "testKeyExists()": FunctionFragment;
    "testTestSetup()": FunctionFragment;
    "testUnfollowAsUnfollowerApprovedDelegatedExecutor(uint256)": FunctionFragment;
    "testUnfollowAsUnfollowerOwner()": FunctionFragment;
    "testUnfollowIfTargetProfileWasBurned()": FunctionFragment;
    "testUnfollowMetaTxTest()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "IS_SCRIPT"
      | "IS_TEST"
      | "excludeArtifacts"
      | "excludeContracts"
      | "excludeSenders"
      | "failed"
      | "keyExists"
      | "setUp"
      | "targetArtifactSelectors"
      | "targetArtifacts"
      | "targetContracts"
      | "targetSelectors"
      | "targetSenders"
      | "testArrayHelpers"
      | "testBaseTest"
      | "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId"
      | "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name"
      | "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber"
      | "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract"
      | "testCannotExecuteMetaTx_WhenSignature_HasExpired"
      | "testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid"
      | "testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented"
      | "testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid"
      | "testCannotUnfollowIfNotFollowingTheTargetProfile"
      | "testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor"
      | "testCannotUnfollowIfPaused"
      | "testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist"
      | "testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore"
      | "testCannotUnfollowIfUnfollowerProfileDoesNotExist"
      | "testContractAddressesLoaderDeployer"
      | "testForkManagement"
      | "testKeyExists"
      | "testTestSetup"
      | "testUnfollowAsUnfollowerApprovedDelegatedExecutor"
      | "testUnfollowAsUnfollowerOwner"
      | "testUnfollowIfTargetProfileWasBurned"
      | "testUnfollowMetaTxTest"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "IS_SCRIPT", values?: undefined): string;
  encodeFunctionData(functionFragment: "IS_TEST", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "excludeArtifacts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeSenders",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "failed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "keyExists",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "targetArtifactSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetArtifacts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetSenders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testArrayHelpers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testBaseTest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotExecuteMetaTx_WhenSignature_HasExpired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotUnfollowIfNotFollowingTheTargetProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotUnfollowIfPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotUnfollowIfUnfollowerProfileDoesNotExist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testContractAddressesLoaderDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testForkManagement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testKeyExists",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testTestSetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testUnfollowAsUnfollowerApprovedDelegatedExecutor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testUnfollowAsUnfollowerOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testUnfollowIfTargetProfileWasBurned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testUnfollowMetaTxTest",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "IS_SCRIPT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IS_TEST", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "excludeArtifacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "failed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keyExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "targetArtifactSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetArtifacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testArrayHelpers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testBaseTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotExecuteMetaTx_WhenSignature_HasExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotUnfollowIfNotFollowingTheTargetProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotUnfollowIfPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotUnfollowIfUnfollowerProfileDoesNotExist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testContractAddressesLoaderDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testForkManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testKeyExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testTestSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testUnfollowAsUnfollowerApprovedDelegatedExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testUnfollowAsUnfollowerOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testUnfollowIfTargetProfileWasBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testUnfollowMetaTxTest",
    data: BytesLike
  ): Result;

  events: {
    "Unfollowed(uint256,uint256,address,uint256)": EventFragment;
    "log(string)": EventFragment;
    "log_address(address)": EventFragment;
    "log_array(uint256[])": EventFragment;
    "log_array(int256[])": EventFragment;
    "log_array(address[])": EventFragment;
    "log_bytes(bytes)": EventFragment;
    "log_bytes32(bytes32)": EventFragment;
    "log_int(int256)": EventFragment;
    "log_named_address(string,address)": EventFragment;
    "log_named_array(string,uint256[])": EventFragment;
    "log_named_array(string,int256[])": EventFragment;
    "log_named_array(string,address[])": EventFragment;
    "log_named_bytes(string,bytes)": EventFragment;
    "log_named_bytes32(string,bytes32)": EventFragment;
    "log_named_decimal_int(string,int256,uint256)": EventFragment;
    "log_named_decimal_uint(string,uint256,uint256)": EventFragment;
    "log_named_int(string,int256)": EventFragment;
    "log_named_string(string,string)": EventFragment;
    "log_named_uint(string,uint256)": EventFragment;
    "log_string(string)": EventFragment;
    "log_uint(uint256)": EventFragment;
    "logs(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Unfollowed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(uint256[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(int256[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(address[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_address"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,uint256[])"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,int256[])"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,address[])"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logs"): EventFragment;
}

export interface UnfollowedEventObject {
  unfollowerProfileId: BigNumber;
  idOfProfileUnfollowed: BigNumber;
  transactionExecutor: string;
  timestamp: BigNumber;
}
export type UnfollowedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber],
  UnfollowedEventObject
>;

export type UnfollowedEventFilter = TypedEventFilter<UnfollowedEvent>;

export interface logEventObject {
  arg0: string;
}
export type logEvent = TypedEvent<[string], logEventObject>;

export type logEventFilter = TypedEventFilter<logEvent>;

export interface log_addressEventObject {
  arg0: string;
}
export type log_addressEvent = TypedEvent<[string], log_addressEventObject>;

export type log_addressEventFilter = TypedEventFilter<log_addressEvent>;

export interface log_array_uint256_array_EventObject {
  val: BigNumber[];
}
export type log_array_uint256_array_Event = TypedEvent<
  [BigNumber[]],
  log_array_uint256_array_EventObject
>;

export type log_array_uint256_array_EventFilter =
  TypedEventFilter<log_array_uint256_array_Event>;

export interface log_array_int256_array_EventObject {
  val: BigNumber[];
}
export type log_array_int256_array_Event = TypedEvent<
  [BigNumber[]],
  log_array_int256_array_EventObject
>;

export type log_array_int256_array_EventFilter =
  TypedEventFilter<log_array_int256_array_Event>;

export interface log_array_address_array_EventObject {
  val: string[];
}
export type log_array_address_array_Event = TypedEvent<
  [string[]],
  log_array_address_array_EventObject
>;

export type log_array_address_array_EventFilter =
  TypedEventFilter<log_array_address_array_Event>;

export interface log_bytesEventObject {
  arg0: string;
}
export type log_bytesEvent = TypedEvent<[string], log_bytesEventObject>;

export type log_bytesEventFilter = TypedEventFilter<log_bytesEvent>;

export interface log_bytes32EventObject {
  arg0: string;
}
export type log_bytes32Event = TypedEvent<[string], log_bytes32EventObject>;

export type log_bytes32EventFilter = TypedEventFilter<log_bytes32Event>;

export interface log_intEventObject {
  arg0: BigNumber;
}
export type log_intEvent = TypedEvent<[BigNumber], log_intEventObject>;

export type log_intEventFilter = TypedEventFilter<log_intEvent>;

export interface log_named_addressEventObject {
  key: string;
  val: string;
}
export type log_named_addressEvent = TypedEvent<
  [string, string],
  log_named_addressEventObject
>;

export type log_named_addressEventFilter =
  TypedEventFilter<log_named_addressEvent>;

export interface log_named_array_string_uint256_array_EventObject {
  key: string;
  val: BigNumber[];
}
export type log_named_array_string_uint256_array_Event = TypedEvent<
  [string, BigNumber[]],
  log_named_array_string_uint256_array_EventObject
>;

export type log_named_array_string_uint256_array_EventFilter =
  TypedEventFilter<log_named_array_string_uint256_array_Event>;

export interface log_named_array_string_int256_array_EventObject {
  key: string;
  val: BigNumber[];
}
export type log_named_array_string_int256_array_Event = TypedEvent<
  [string, BigNumber[]],
  log_named_array_string_int256_array_EventObject
>;

export type log_named_array_string_int256_array_EventFilter =
  TypedEventFilter<log_named_array_string_int256_array_Event>;

export interface log_named_array_string_address_array_EventObject {
  key: string;
  val: string[];
}
export type log_named_array_string_address_array_Event = TypedEvent<
  [string, string[]],
  log_named_array_string_address_array_EventObject
>;

export type log_named_array_string_address_array_EventFilter =
  TypedEventFilter<log_named_array_string_address_array_Event>;

export interface log_named_bytesEventObject {
  key: string;
  val: string;
}
export type log_named_bytesEvent = TypedEvent<
  [string, string],
  log_named_bytesEventObject
>;

export type log_named_bytesEventFilter = TypedEventFilter<log_named_bytesEvent>;

export interface log_named_bytes32EventObject {
  key: string;
  val: string;
}
export type log_named_bytes32Event = TypedEvent<
  [string, string],
  log_named_bytes32EventObject
>;

export type log_named_bytes32EventFilter =
  TypedEventFilter<log_named_bytes32Event>;

export interface log_named_decimal_intEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_intEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_intEventObject
>;

export type log_named_decimal_intEventFilter =
  TypedEventFilter<log_named_decimal_intEvent>;

export interface log_named_decimal_uintEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_uintEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_uintEventObject
>;

export type log_named_decimal_uintEventFilter =
  TypedEventFilter<log_named_decimal_uintEvent>;

export interface log_named_intEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_intEvent = TypedEvent<
  [string, BigNumber],
  log_named_intEventObject
>;

export type log_named_intEventFilter = TypedEventFilter<log_named_intEvent>;

export interface log_named_stringEventObject {
  key: string;
  val: string;
}
export type log_named_stringEvent = TypedEvent<
  [string, string],
  log_named_stringEventObject
>;

export type log_named_stringEventFilter =
  TypedEventFilter<log_named_stringEvent>;

export interface log_named_uintEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_uintEvent = TypedEvent<
  [string, BigNumber],
  log_named_uintEventObject
>;

export type log_named_uintEventFilter = TypedEventFilter<log_named_uintEvent>;

export interface log_stringEventObject {
  arg0: string;
}
export type log_stringEvent = TypedEvent<[string], log_stringEventObject>;

export type log_stringEventFilter = TypedEventFilter<log_stringEvent>;

export interface log_uintEventObject {
  arg0: BigNumber;
}
export type log_uintEvent = TypedEvent<[BigNumber], log_uintEventObject>;

export type log_uintEventFilter = TypedEventFilter<log_uintEvent>;

export interface logsEventObject {
  arg0: string;
}
export type logsEvent = TypedEvent<[string], logsEventObject>;

export type logsEventFilter = TypedEventFilter<logsEvent>;

export interface UnfollowMetaTxTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UnfollowMetaTxTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<[boolean]>;

    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    excludeArtifacts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedArtifacts_: string[] }>;

    excludeContracts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedContracts_: string[] }>;

    excludeSenders(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedSenders_: string[] }>;

    failed(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    keyExists(
      json: string,
      key: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzSelectorStructOutput[]] & {
        targetedArtifactSelectors_: StdInvariant.FuzzSelectorStructOutput[];
      }
    >;

    targetArtifacts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedArtifacts_: string[] }>;

    targetContracts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedContracts_: string[] }>;

    targetSelectors(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzSelectorStructOutput[]] & {
        targetedSelectors_: StdInvariant.FuzzSelectorStructOutput[];
      }
    >;

    targetSenders(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedSenders_: string[] }>;

    testArrayHelpers(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testBaseTest(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotExecuteMetaTx_WhenSignature_HasExpired(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotUnfollowIfNotFollowingTheTargetProfile(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor(
      transactionExecutorPk: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotUnfollowIfPaused(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist(
      unexistentProfileId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotUnfollowIfUnfollowerProfileDoesNotExist(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testContractAddressesLoaderDeployer(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testForkManagement(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testKeyExists(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testTestSetup(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testUnfollowAsUnfollowerApprovedDelegatedExecutor(
      approvedDelegatedExecutorPk: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testUnfollowAsUnfollowerOwner(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testUnfollowIfTargetProfileWasBurned(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testUnfollowMetaTxTest(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  excludeArtifacts(overrides?: CallOverrides): Promise<string[]>;

  excludeContracts(overrides?: CallOverrides): Promise<string[]>;

  excludeSenders(overrides?: CallOverrides): Promise<string[]>;

  failed(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  keyExists(
    json: string,
    key: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setUp(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  targetArtifactSelectors(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

  targetArtifacts(overrides?: CallOverrides): Promise<string[]>;

  targetContracts(overrides?: CallOverrides): Promise<string[]>;

  targetSelectors(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

  targetSenders(overrides?: CallOverrides): Promise<string[]>;

  testArrayHelpers(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testBaseTest(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotExecuteMetaTx_WhenSignature_HasExpired(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotUnfollowIfNotFollowingTheTargetProfile(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor(
    transactionExecutorPk: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotUnfollowIfPaused(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist(
    unexistentProfileId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotUnfollowIfUnfollowerProfileDoesNotExist(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testContractAddressesLoaderDeployer(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testForkManagement(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testKeyExists(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testTestSetup(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testUnfollowAsUnfollowerApprovedDelegatedExecutor(
    approvedDelegatedExecutorPk: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testUnfollowAsUnfollowerOwner(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testUnfollowIfTargetProfileWasBurned(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testUnfollowMetaTxTest(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    excludeArtifacts(overrides?: CallOverrides): Promise<string[]>;

    excludeContracts(overrides?: CallOverrides): Promise<string[]>;

    excludeSenders(overrides?: CallOverrides): Promise<string[]>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    keyExists(
      json: string,
      key: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setUp(overrides?: CallOverrides): Promise<void>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

    targetArtifacts(overrides?: CallOverrides): Promise<string[]>;

    targetContracts(overrides?: CallOverrides): Promise<string[]>;

    targetSelectors(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

    targetSenders(overrides?: CallOverrides): Promise<string[]>;

    testArrayHelpers(overrides?: CallOverrides): Promise<void>;

    testBaseTest(overrides?: CallOverrides): Promise<void>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotExecuteMetaTx_WhenSignature_HasExpired(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotUnfollowIfNotFollowingTheTargetProfile(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor(
      transactionExecutorPk: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotUnfollowIfPaused(overrides?: CallOverrides): Promise<void>;

    testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist(
      unexistentProfileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotUnfollowIfUnfollowerProfileDoesNotExist(
      overrides?: CallOverrides
    ): Promise<void>;

    testContractAddressesLoaderDeployer(
      overrides?: CallOverrides
    ): Promise<void>;

    testForkManagement(overrides?: CallOverrides): Promise<void>;

    testKeyExists(overrides?: CallOverrides): Promise<void>;

    testTestSetup(overrides?: CallOverrides): Promise<void>;

    testUnfollowAsUnfollowerApprovedDelegatedExecutor(
      approvedDelegatedExecutorPk: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    testUnfollowAsUnfollowerOwner(overrides?: CallOverrides): Promise<void>;

    testUnfollowIfTargetProfileWasBurned(
      overrides?: CallOverrides
    ): Promise<void>;

    testUnfollowMetaTxTest(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Unfollowed(uint256,uint256,address,uint256)"(
      unfollowerProfileId?: BigNumberish | null,
      idOfProfileUnfollowed?: null,
      transactionExecutor?: null,
      timestamp?: null
    ): UnfollowedEventFilter;
    Unfollowed(
      unfollowerProfileId?: BigNumberish | null,
      idOfProfileUnfollowed?: null,
      transactionExecutor?: null,
      timestamp?: null
    ): UnfollowedEventFilter;

    "log(string)"(arg0?: null): logEventFilter;
    log(arg0?: null): logEventFilter;

    "log_address(address)"(arg0?: null): log_addressEventFilter;
    log_address(arg0?: null): log_addressEventFilter;

    "log_array(uint256[])"(val?: null): log_array_uint256_array_EventFilter;
    "log_array(int256[])"(val?: null): log_array_int256_array_EventFilter;
    "log_array(address[])"(val?: null): log_array_address_array_EventFilter;

    "log_bytes(bytes)"(arg0?: null): log_bytesEventFilter;
    log_bytes(arg0?: null): log_bytesEventFilter;

    "log_bytes32(bytes32)"(arg0?: null): log_bytes32EventFilter;
    log_bytes32(arg0?: null): log_bytes32EventFilter;

    "log_int(int256)"(arg0?: null): log_intEventFilter;
    log_int(arg0?: null): log_intEventFilter;

    "log_named_address(string,address)"(
      key?: null,
      val?: null
    ): log_named_addressEventFilter;
    log_named_address(key?: null, val?: null): log_named_addressEventFilter;

    "log_named_array(string,uint256[])"(
      key?: null,
      val?: null
    ): log_named_array_string_uint256_array_EventFilter;
    "log_named_array(string,int256[])"(
      key?: null,
      val?: null
    ): log_named_array_string_int256_array_EventFilter;
    "log_named_array(string,address[])"(
      key?: null,
      val?: null
    ): log_named_array_string_address_array_EventFilter;

    "log_named_bytes(string,bytes)"(
      key?: null,
      val?: null
    ): log_named_bytesEventFilter;
    log_named_bytes(key?: null, val?: null): log_named_bytesEventFilter;

    "log_named_bytes32(string,bytes32)"(
      key?: null,
      val?: null
    ): log_named_bytes32EventFilter;
    log_named_bytes32(key?: null, val?: null): log_named_bytes32EventFilter;

    "log_named_decimal_int(string,int256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;
    log_named_decimal_int(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;

    "log_named_decimal_uint(string,uint256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;
    log_named_decimal_uint(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;

    "log_named_int(string,int256)"(
      key?: null,
      val?: null
    ): log_named_intEventFilter;
    log_named_int(key?: null, val?: null): log_named_intEventFilter;

    "log_named_string(string,string)"(
      key?: null,
      val?: null
    ): log_named_stringEventFilter;
    log_named_string(key?: null, val?: null): log_named_stringEventFilter;

    "log_named_uint(string,uint256)"(
      key?: null,
      val?: null
    ): log_named_uintEventFilter;
    log_named_uint(key?: null, val?: null): log_named_uintEventFilter;

    "log_string(string)"(arg0?: null): log_stringEventFilter;
    log_string(arg0?: null): log_stringEventFilter;

    "log_uint(uint256)"(arg0?: null): log_uintEventFilter;
    log_uint(arg0?: null): log_uintEventFilter;

    "logs(bytes)"(arg0?: null): logsEventFilter;
    logs(arg0?: null): logsEventFilter;
  };

  estimateGas: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<BigNumber>;

    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    excludeArtifacts(overrides?: CallOverrides): Promise<BigNumber>;

    excludeContracts(overrides?: CallOverrides): Promise<BigNumber>;

    excludeSenders(overrides?: CallOverrides): Promise<BigNumber>;

    failed(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    keyExists(
      json: string,
      key: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setUp(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    targetArtifactSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    targetArtifacts(overrides?: CallOverrides): Promise<BigNumber>;

    targetContracts(overrides?: CallOverrides): Promise<BigNumber>;

    targetSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    targetSenders(overrides?: CallOverrides): Promise<BigNumber>;

    testArrayHelpers(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testBaseTest(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotExecuteMetaTx_WhenSignature_HasExpired(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotUnfollowIfNotFollowingTheTargetProfile(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor(
      transactionExecutorPk: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotUnfollowIfPaused(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist(
      unexistentProfileId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotUnfollowIfUnfollowerProfileDoesNotExist(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testContractAddressesLoaderDeployer(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testForkManagement(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testKeyExists(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testTestSetup(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testUnfollowAsUnfollowerApprovedDelegatedExecutor(
      approvedDelegatedExecutorPk: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testUnfollowAsUnfollowerOwner(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testUnfollowIfTargetProfileWasBurned(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testUnfollowMetaTxTest(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeArtifacts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeSenders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failed(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    keyExists(
      json: string,
      key: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    targetArtifacts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetSelectors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetSenders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testArrayHelpers(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testBaseTest(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_ChainId(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_Name(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_RevisionNumber(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotExecuteMetaTx_WhenSignatureDomain_WasGeneratedWithWrong_VerifyingContract(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotExecuteMetaTx_WhenSignature_HasExpired(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotExecuteMetaTx_WhenSignature_NonceIsInvalid(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotExecuteMetaTx_WhenSignature_NonceWasIncremented(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotExecuteMetaTx_WhenSignature_SignerIsInvalid(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotUnfollowIfNotFollowingTheTargetProfile(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotUnfollowIfNotProfileOwnerOrDelegatedExecutor(
      transactionExecutorPk: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotUnfollowIfPaused(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotUnfollowIfSomeOfTheProfilesToUnfollowDoNotExist(
      unexistentProfileId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotUnfollowIfTheProfileHasNeverBeenFollowedBefore(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotUnfollowIfUnfollowerProfileDoesNotExist(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testContractAddressesLoaderDeployer(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testForkManagement(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testKeyExists(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testTestSetup(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testUnfollowAsUnfollowerApprovedDelegatedExecutor(
      approvedDelegatedExecutorPk: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testUnfollowAsUnfollowerOwner(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testUnfollowIfTargetProfileWasBurned(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testUnfollowMetaTxTest(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
