/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { DiGiModule, DiGiModuleInterface } from "../DiGiModule";

const _abi = [
  {
    type: "function",
    name: "getModuleMetadataURI",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [
      {
        name: "interfaceID",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "pure",
  },
] as const;

export class DiGiModule__factory {
  static readonly abi = _abi;
  static createInterface(): DiGiModuleInterface {
    return new utils.Interface(_abi) as DiGiModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DiGiModule {
    return new Contract(address, _abi, signerOrProvider) as DiGiModule;
  }
}
