/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenHandleRegistry,
  ITokenHandleRegistryInterface,
} from "../ITokenHandleRegistry";

const _abi = [
  {
    type: "function",
    name: "getDefaultHandle",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "link",
    inputs: [
      {
        name: "handleId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "profileId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "migrationLink",
    inputs: [
      {
        name: "handleId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "profileId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolve",
    inputs: [
      {
        name: "handleId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unlink",
    inputs: [
      {
        name: "handleId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "profileId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class ITokenHandleRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenHandleRegistryInterface {
    return new utils.Interface(_abi) as ITokenHandleRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenHandleRegistry {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITokenHandleRegistry;
  }
}
