/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockDeprecatedFollowModule,
  MockDeprecatedFollowModuleInterface,
} from "../MockDeprecatedFollowModule";

const _abi = [
  {
    type: "function",
    name: "followModuleTransferHook",
    inputs: [
      {
        name: "profileId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "from",
        type: "address",
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        internalType: "address",
      },
      {
        name: "followNFTTokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initializeFollowModule",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "isFollowing",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "processFollow",
    inputs: [
      {
        name: "follower",
        type: "address",
        internalType: "address",
      },
      {
        name: "profileId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "testMockDeprecatedFollowModule",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610290908161001c8239f35b600080fdfe6080604081815260048036101561001557600080fd5b600092833560e01c9081630e096ae1146101cb5781633cb22cc41461019b578163451c3d0c14610176575080635ff452991461015f57639713958a1461005a57600080fd5b346101575781600319360112610157576001600160401b039260243584811161015b5761008a903690840161022d565b908095916020968791810103126101575760019035036101185783519285840191821184831017610105575083949291945283815282519382859384528251928382860152825b8481106100ef57505050828201840152601f01601f19168101030190f35b81810183015188820188015287955082016100d1565b634e487b7160e01b835260419052602482fd5b835162461bcd60e51b81528084018690526019602482015278135bd8dad19bdb1b1bddd35bd91d5b194e881a5b9d985b1a59603a1b6044820152606490fd5b8280fd5b5080fd5b833461017357806003193601126101735780f35b80fd5b84903461015b57606036600319011261015b57602090610194610212565b5060018152f35b8434610173576080366003190112610173576101b5610212565b506044356001600160a01b038116036101735780f35b84833461015b57606036600319011261015b5780356001600160a01b0381160361015b57604435906001600160401b0382116101575761020d9136910161022d565b505080f35b602435906001600160a01b038216820361022857565b600080fd5b9181601f84011215610228578235916001600160401b03831161022857602083818601950101116102285756fea2646970667358221220c0db28bdce0c8df30c8cc6b1b15a9e14c01b7024592aad1a5c0a7b900ea91d6264736f6c63430008150033";

type MockDeprecatedFollowModuleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockDeprecatedFollowModuleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockDeprecatedFollowModule__factory extends ContractFactory {
  constructor(...args: MockDeprecatedFollowModuleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<MockDeprecatedFollowModule> {
    return super.deploy(overrides || {}) as Promise<MockDeprecatedFollowModule>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MockDeprecatedFollowModule {
    return super.attach(address) as MockDeprecatedFollowModule;
  }
  override connect(signer: Signer): MockDeprecatedFollowModule__factory {
    return super.connect(signer) as MockDeprecatedFollowModule__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockDeprecatedFollowModuleInterface {
    return new utils.Interface(_abi) as MockDeprecatedFollowModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockDeprecatedFollowModule {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockDeprecatedFollowModule;
  }
}
