/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TokenGatedReferenceModuleBase } from "./TokenGatedReferenceModuleBase";
export type { TokenGatedReferenceModule_ERC20_Gated } from "./TokenGatedReferenceModule_ERC20_Gated";
export type { TokenGatedReferenceModule_ERC721_Gated } from "./TokenGatedReferenceModule_ERC721_Gated";
export type { TokenGatedReferenceModule_Publication } from "./TokenGatedReferenceModule_Publication";
