/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface MockNonDiGiHubGovernedInterface extends utils.Interface {
  functions: {
    "failWithCustomError()": FunctionFragment;
    "failWithNoErrorData()": FunctionFragment;
    "failWithPanic()": FunctionFragment;
    "failWithStringRevert()": FunctionFragment;
    "governance()": FunctionFragment;
    "requiresGovernance(bool)": FunctionFragment;
    "testMockNonDiGiHubGoverned()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "failWithCustomError"
      | "failWithNoErrorData"
      | "failWithPanic"
      | "failWithStringRevert"
      | "governance"
      | "requiresGovernance"
      | "testMockNonDiGiHubGoverned"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "failWithCustomError",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "failWithNoErrorData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "failWithPanic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "failWithStringRevert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiresGovernance",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "testMockNonDiGiHubGoverned",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "failWithCustomError",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "failWithNoErrorData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "failWithPanic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "failWithStringRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requiresGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testMockNonDiGiHubGoverned",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MockNonDiGiHubGoverned extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockNonDiGiHubGovernedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    failWithCustomError(overrides?: CallOverrides): Promise<[void]>;

    failWithNoErrorData(overrides?: CallOverrides): Promise<[void]>;

    failWithPanic(overrides?: CallOverrides): Promise<[void]>;

    failWithStringRevert(overrides?: CallOverrides): Promise<[void]>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    requiresGovernance(
      pass: boolean,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    testMockNonDiGiHubGoverned(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  failWithCustomError(overrides?: CallOverrides): Promise<void>;

  failWithNoErrorData(overrides?: CallOverrides): Promise<void>;

  failWithPanic(overrides?: CallOverrides): Promise<void>;

  failWithStringRevert(overrides?: CallOverrides): Promise<void>;

  governance(overrides?: CallOverrides): Promise<string>;

  requiresGovernance(
    pass: boolean,
    overrides?: CallOverrides
  ): Promise<boolean>;

  testMockNonDiGiHubGoverned(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    failWithCustomError(overrides?: CallOverrides): Promise<void>;

    failWithNoErrorData(overrides?: CallOverrides): Promise<void>;

    failWithPanic(overrides?: CallOverrides): Promise<void>;

    failWithStringRevert(overrides?: CallOverrides): Promise<void>;

    governance(overrides?: CallOverrides): Promise<string>;

    requiresGovernance(
      pass: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    testMockNonDiGiHubGoverned(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    failWithCustomError(overrides?: CallOverrides): Promise<BigNumber>;

    failWithNoErrorData(overrides?: CallOverrides): Promise<BigNumber>;

    failWithPanic(overrides?: CallOverrides): Promise<BigNumber>;

    failWithStringRevert(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    requiresGovernance(
      pass: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testMockNonDiGiHubGoverned(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    failWithCustomError(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    failWithNoErrorData(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    failWithPanic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failWithStringRevert(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requiresGovernance(
      pass: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testMockNonDiGiHubGoverned(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
