/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TokenHandleRegistryLinkMetaTxTest__factory } from "./TokenHandleRegistryLinkMetaTxTest__factory";
export { TokenHandleRegistryMetaTxBaseTest__factory } from "./TokenHandleRegistryMetaTxBaseTest__factory";
export { TokenHandleRegistryTest__factory } from "./TokenHandleRegistryTest__factory";
export { TokenHandleRegistryUnlinkMetaTxTest__factory } from "./TokenHandleRegistryUnlinkMetaTxTest__factory";
