/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  Signer,
  utils,
} from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface FollowLibInterface extends utils.Interface {
  functions: {};

  events: {
    "FollowNFTDeployed(uint256,address,uint256)": EventFragment;
    "Followed(uint256,uint256,uint256,bytes,bytes,address,uint256)": EventFragment;
    "Unfollowed(uint256,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FollowNFTDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Followed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unfollowed"): EventFragment;
}

export interface FollowNFTDeployedEventObject {
  profileId: BigNumber;
  followNFT: string;
  timestamp: BigNumber;
}
export type FollowNFTDeployedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  FollowNFTDeployedEventObject
>;

export type FollowNFTDeployedEventFilter =
  TypedEventFilter<FollowNFTDeployedEvent>;

export interface FollowedEventObject {
  followerProfileId: BigNumber;
  idOfProfileFollowed: BigNumber;
  followTokenIdAssigned: BigNumber;
  followModuleData: string;
  processFollowModuleReturnData: string;
  transactionExecutor: string;
  timestamp: BigNumber;
}
export type FollowedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, string, string, string, BigNumber],
  FollowedEventObject
>;

export type FollowedEventFilter = TypedEventFilter<FollowedEvent>;

export interface UnfollowedEventObject {
  unfollowerProfileId: BigNumber;
  idOfProfileUnfollowed: BigNumber;
  transactionExecutor: string;
  timestamp: BigNumber;
}
export type UnfollowedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber],
  UnfollowedEventObject
>;

export type UnfollowedEventFilter = TypedEventFilter<UnfollowedEvent>;

export interface FollowLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FollowLibInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "FollowNFTDeployed(uint256,address,uint256)"(
      profileId?: BigNumberish | null,
      followNFT?: string | null,
      timestamp?: null
    ): FollowNFTDeployedEventFilter;
    FollowNFTDeployed(
      profileId?: BigNumberish | null,
      followNFT?: string | null,
      timestamp?: null
    ): FollowNFTDeployedEventFilter;

    "Followed(uint256,uint256,uint256,bytes,bytes,address,uint256)"(
      followerProfileId?: BigNumberish | null,
      idOfProfileFollowed?: null,
      followTokenIdAssigned?: null,
      followModuleData?: null,
      processFollowModuleReturnData?: null,
      transactionExecutor?: null,
      timestamp?: null
    ): FollowedEventFilter;
    Followed(
      followerProfileId?: BigNumberish | null,
      idOfProfileFollowed?: null,
      followTokenIdAssigned?: null,
      followModuleData?: null,
      processFollowModuleReturnData?: null,
      transactionExecutor?: null,
      timestamp?: null
    ): FollowedEventFilter;

    "Unfollowed(uint256,uint256,address,uint256)"(
      unfollowerProfileId?: BigNumberish | null,
      idOfProfileUnfollowed?: null,
      transactionExecutor?: null,
      timestamp?: null
    ): UnfollowedEventFilter;
    Unfollowed(
      unfollowerProfileId?: BigNumberish | null,
      idOfProfileUnfollowed?: null,
      transactionExecutor?: null,
      timestamp?: null
    ): UnfollowedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
