/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TokenGatedReferenceModuleBase__factory } from "./TokenGatedReferenceModuleBase__factory";
export { TokenGatedReferenceModule_ERC20_Gated__factory } from "./TokenGatedReferenceModule_ERC20_Gated__factory";
export { TokenGatedReferenceModule_ERC721_Gated__factory } from "./TokenGatedReferenceModule_ERC721_Gated__factory";
export { TokenGatedReferenceModule_Publication__factory } from "./TokenGatedReferenceModule_Publication__factory";
