/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MigrationsTest } from "./MigrationsTest";
export type { MigrationsTestHardcoded } from "./MigrationsTestHardcoded";
export type { MigrationsTestNonFork } from "./MigrationsTestNonFork";
