/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGuardedToken } from "./IGuardedToken";
export type { TokenGuardianTest_Default_Off } from "./TokenGuardianTest_Default_Off";
export type { TokenGuardianTest_Default_On } from "./TokenGuardianTest_Default_On";
