/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ActionablePublicationTest } from "./ActionablePublicationTest";
export type { PublicationTest } from "./PublicationTest";
export type { ReferencePublicationTest } from "./ReferencePublicationTest";
