/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LegacyCollectMetaTxTest__factory } from "./LegacyCollectMetaTxTest__factory";
export { LegacyCollectTest__factory } from "./LegacyCollectTest__factory";
