/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SetBlockStatusMetaTxTest__factory } from "./SetBlockStatusMetaTxTest__factory";
export { SetBlockStatusTest__factory } from "./SetBlockStatusTest__factory";
