/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDiGiHub } from "./IDiGiHub";
export type { IERC721 } from "./IERC721";
export type { IFollowModule } from "./IFollowModule";
export type { MockDeprecatedCollectModuleFollowerOnly } from "./MockDeprecatedCollectModuleFollowerOnly";
