/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace StdInvariant {
  export type FuzzSelectorStruct = { addr: string; selectors: BytesLike[] };

  export type FuzzSelectorStructOutput = [string, string[]] & {
    addr: string;
    selectors: string[];
  };
}

export interface ModuleRegistryTestInterface extends utils.Interface {
  functions: {
    "IS_SCRIPT()": FunctionFragment;
    "IS_TEST()": FunctionFragment;
    "excludeArtifacts()": FunctionFragment;
    "excludeContracts()": FunctionFragment;
    "excludeSenders()": FunctionFragment;
    "failed()": FunctionFragment;
    "keyExists(string,string)": FunctionFragment;
    "setUp()": FunctionFragment;
    "targetArtifactSelectors()": FunctionFragment;
    "targetArtifacts()": FunctionFragment;
    "targetContracts()": FunctionFragment;
    "targetSelectors()": FunctionFragment;
    "targetSenders()": FunctionFragment;
    "testArrayHelpers()": FunctionFragment;
    "testBaseTest()": FunctionFragment;
    "testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax(uint256)": FunctionFragment;
    "testCannotRegisterErc20Currency_Twice()": FunctionFragment;
    "testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface()": FunctionFragment;
    "testCannotRegisterModule_IfModuleDoesNotSupportType()": FunctionFragment;
    "testCannotRegisterModule_IfModuleTypeIsBiggerThanMax(uint256)": FunctionFragment;
    "testCannotRegisterModule_IfModuleTypeIsZero()": FunctionFragment;
    "testCannotRegisterModule_TwiceAsTheSameType()": FunctionFragment;
    "testContractAddressesLoaderDeployer()": FunctionFragment;
    "testForkManagement()": FunctionFragment;
    "testGetModuleTypes_WhenRegisteredAsMultipleTypes()": FunctionFragment;
    "testKeyExists()": FunctionFragment;
    "testRegisterErc20Currency()": FunctionFragment;
    "testRegisterModule_IfSupportsFollowModule(address)": FunctionFragment;
    "testRegisterModule_IfSupportsPublicationActionModule(address)": FunctionFragment;
    "testRegisterModule_IfSupportsReferenceModule(address)": FunctionFragment;
    "testTestSetup()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "IS_SCRIPT"
      | "IS_TEST"
      | "excludeArtifacts"
      | "excludeContracts"
      | "excludeSenders"
      | "failed"
      | "keyExists"
      | "setUp"
      | "targetArtifactSelectors"
      | "targetArtifacts"
      | "targetContracts"
      | "targetSelectors"
      | "targetSenders"
      | "testArrayHelpers"
      | "testBaseTest"
      | "testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax"
      | "testCannotRegisterErc20Currency_Twice"
      | "testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface"
      | "testCannotRegisterModule_IfModuleDoesNotSupportType"
      | "testCannotRegisterModule_IfModuleTypeIsBiggerThanMax"
      | "testCannotRegisterModule_IfModuleTypeIsZero"
      | "testCannotRegisterModule_TwiceAsTheSameType"
      | "testContractAddressesLoaderDeployer"
      | "testForkManagement"
      | "testGetModuleTypes_WhenRegisteredAsMultipleTypes"
      | "testKeyExists"
      | "testRegisterErc20Currency"
      | "testRegisterModule_IfSupportsFollowModule"
      | "testRegisterModule_IfSupportsPublicationActionModule"
      | "testRegisterModule_IfSupportsReferenceModule"
      | "testTestSetup"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "IS_SCRIPT", values?: undefined): string;
  encodeFunctionData(functionFragment: "IS_TEST", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "excludeArtifacts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeSenders",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "failed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "keyExists",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "targetArtifactSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetArtifacts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetSenders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testArrayHelpers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testBaseTest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotRegisterErc20Currency_Twice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotRegisterModule_IfModuleDoesNotSupportType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotRegisterModule_IfModuleTypeIsBiggerThanMax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotRegisterModule_IfModuleTypeIsZero",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotRegisterModule_TwiceAsTheSameType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testContractAddressesLoaderDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testForkManagement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testGetModuleTypes_WhenRegisteredAsMultipleTypes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testKeyExists",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRegisterErc20Currency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRegisterModule_IfSupportsFollowModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "testRegisterModule_IfSupportsPublicationActionModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "testRegisterModule_IfSupportsReferenceModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "testTestSetup",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "IS_SCRIPT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IS_TEST", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "excludeArtifacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "failed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keyExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "targetArtifactSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetArtifacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testArrayHelpers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testBaseTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotRegisterErc20Currency_Twice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotRegisterModule_IfModuleDoesNotSupportType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotRegisterModule_IfModuleTypeIsBiggerThanMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotRegisterModule_IfModuleTypeIsZero",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotRegisterModule_TwiceAsTheSameType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testContractAddressesLoaderDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testForkManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testGetModuleTypes_WhenRegisteredAsMultipleTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testKeyExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRegisterErc20Currency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRegisterModule_IfSupportsFollowModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRegisterModule_IfSupportsPublicationActionModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRegisterModule_IfSupportsReferenceModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testTestSetup",
    data: BytesLike
  ): Result;

  events: {
    "log(string)": EventFragment;
    "log_address(address)": EventFragment;
    "log_array(uint256[])": EventFragment;
    "log_array(int256[])": EventFragment;
    "log_array(address[])": EventFragment;
    "log_bytes(bytes)": EventFragment;
    "log_bytes32(bytes32)": EventFragment;
    "log_int(int256)": EventFragment;
    "log_named_address(string,address)": EventFragment;
    "log_named_array(string,uint256[])": EventFragment;
    "log_named_array(string,int256[])": EventFragment;
    "log_named_array(string,address[])": EventFragment;
    "log_named_bytes(string,bytes)": EventFragment;
    "log_named_bytes32(string,bytes32)": EventFragment;
    "log_named_decimal_int(string,int256,uint256)": EventFragment;
    "log_named_decimal_uint(string,uint256,uint256)": EventFragment;
    "log_named_int(string,int256)": EventFragment;
    "log_named_string(string,string)": EventFragment;
    "log_named_uint(string,uint256)": EventFragment;
    "log_string(string)": EventFragment;
    "log_uint(uint256)": EventFragment;
    "logs(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "log"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(uint256[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(int256[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(address[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_address"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,uint256[])"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,int256[])"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,address[])"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logs"): EventFragment;
}

export interface logEventObject {
  arg0: string;
}
export type logEvent = TypedEvent<[string], logEventObject>;

export type logEventFilter = TypedEventFilter<logEvent>;

export interface log_addressEventObject {
  arg0: string;
}
export type log_addressEvent = TypedEvent<[string], log_addressEventObject>;

export type log_addressEventFilter = TypedEventFilter<log_addressEvent>;

export interface log_array_uint256_array_EventObject {
  val: BigNumber[];
}
export type log_array_uint256_array_Event = TypedEvent<
  [BigNumber[]],
  log_array_uint256_array_EventObject
>;

export type log_array_uint256_array_EventFilter =
  TypedEventFilter<log_array_uint256_array_Event>;

export interface log_array_int256_array_EventObject {
  val: BigNumber[];
}
export type log_array_int256_array_Event = TypedEvent<
  [BigNumber[]],
  log_array_int256_array_EventObject
>;

export type log_array_int256_array_EventFilter =
  TypedEventFilter<log_array_int256_array_Event>;

export interface log_array_address_array_EventObject {
  val: string[];
}
export type log_array_address_array_Event = TypedEvent<
  [string[]],
  log_array_address_array_EventObject
>;

export type log_array_address_array_EventFilter =
  TypedEventFilter<log_array_address_array_Event>;

export interface log_bytesEventObject {
  arg0: string;
}
export type log_bytesEvent = TypedEvent<[string], log_bytesEventObject>;

export type log_bytesEventFilter = TypedEventFilter<log_bytesEvent>;

export interface log_bytes32EventObject {
  arg0: string;
}
export type log_bytes32Event = TypedEvent<[string], log_bytes32EventObject>;

export type log_bytes32EventFilter = TypedEventFilter<log_bytes32Event>;

export interface log_intEventObject {
  arg0: BigNumber;
}
export type log_intEvent = TypedEvent<[BigNumber], log_intEventObject>;

export type log_intEventFilter = TypedEventFilter<log_intEvent>;

export interface log_named_addressEventObject {
  key: string;
  val: string;
}
export type log_named_addressEvent = TypedEvent<
  [string, string],
  log_named_addressEventObject
>;

export type log_named_addressEventFilter =
  TypedEventFilter<log_named_addressEvent>;

export interface log_named_array_string_uint256_array_EventObject {
  key: string;
  val: BigNumber[];
}
export type log_named_array_string_uint256_array_Event = TypedEvent<
  [string, BigNumber[]],
  log_named_array_string_uint256_array_EventObject
>;

export type log_named_array_string_uint256_array_EventFilter =
  TypedEventFilter<log_named_array_string_uint256_array_Event>;

export interface log_named_array_string_int256_array_EventObject {
  key: string;
  val: BigNumber[];
}
export type log_named_array_string_int256_array_Event = TypedEvent<
  [string, BigNumber[]],
  log_named_array_string_int256_array_EventObject
>;

export type log_named_array_string_int256_array_EventFilter =
  TypedEventFilter<log_named_array_string_int256_array_Event>;

export interface log_named_array_string_address_array_EventObject {
  key: string;
  val: string[];
}
export type log_named_array_string_address_array_Event = TypedEvent<
  [string, string[]],
  log_named_array_string_address_array_EventObject
>;

export type log_named_array_string_address_array_EventFilter =
  TypedEventFilter<log_named_array_string_address_array_Event>;

export interface log_named_bytesEventObject {
  key: string;
  val: string;
}
export type log_named_bytesEvent = TypedEvent<
  [string, string],
  log_named_bytesEventObject
>;

export type log_named_bytesEventFilter = TypedEventFilter<log_named_bytesEvent>;

export interface log_named_bytes32EventObject {
  key: string;
  val: string;
}
export type log_named_bytes32Event = TypedEvent<
  [string, string],
  log_named_bytes32EventObject
>;

export type log_named_bytes32EventFilter =
  TypedEventFilter<log_named_bytes32Event>;

export interface log_named_decimal_intEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_intEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_intEventObject
>;

export type log_named_decimal_intEventFilter =
  TypedEventFilter<log_named_decimal_intEvent>;

export interface log_named_decimal_uintEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_uintEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_uintEventObject
>;

export type log_named_decimal_uintEventFilter =
  TypedEventFilter<log_named_decimal_uintEvent>;

export interface log_named_intEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_intEvent = TypedEvent<
  [string, BigNumber],
  log_named_intEventObject
>;

export type log_named_intEventFilter = TypedEventFilter<log_named_intEvent>;

export interface log_named_stringEventObject {
  key: string;
  val: string;
}
export type log_named_stringEvent = TypedEvent<
  [string, string],
  log_named_stringEventObject
>;

export type log_named_stringEventFilter =
  TypedEventFilter<log_named_stringEvent>;

export interface log_named_uintEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_uintEvent = TypedEvent<
  [string, BigNumber],
  log_named_uintEventObject
>;

export type log_named_uintEventFilter = TypedEventFilter<log_named_uintEvent>;

export interface log_stringEventObject {
  arg0: string;
}
export type log_stringEvent = TypedEvent<[string], log_stringEventObject>;

export type log_stringEventFilter = TypedEventFilter<log_stringEvent>;

export interface log_uintEventObject {
  arg0: BigNumber;
}
export type log_uintEvent = TypedEvent<[BigNumber], log_uintEventObject>;

export type log_uintEventFilter = TypedEventFilter<log_uintEvent>;

export interface logsEventObject {
  arg0: string;
}
export type logsEvent = TypedEvent<[string], logsEventObject>;

export type logsEventFilter = TypedEventFilter<logsEvent>;

export interface ModuleRegistryTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ModuleRegistryTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<[boolean]>;

    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    excludeArtifacts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedArtifacts_: string[] }>;

    excludeContracts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedContracts_: string[] }>;

    excludeSenders(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedSenders_: string[] }>;

    failed(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    keyExists(
      json: string,
      key: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzSelectorStructOutput[]] & {
        targetedArtifactSelectors_: StdInvariant.FuzzSelectorStructOutput[];
      }
    >;

    targetArtifacts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedArtifacts_: string[] }>;

    targetContracts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedContracts_: string[] }>;

    targetSelectors(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzSelectorStructOutput[]] & {
        targetedSelectors_: StdInvariant.FuzzSelectorStructOutput[];
      }
    >;

    targetSenders(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedSenders_: string[] }>;

    testArrayHelpers(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testBaseTest(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax(
      moduleType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotRegisterErc20Currency_Twice(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotRegisterModule_IfModuleDoesNotSupportType(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotRegisterModule_IfModuleTypeIsBiggerThanMax(
      moduleType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotRegisterModule_IfModuleTypeIsZero(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testCannotRegisterModule_TwiceAsTheSameType(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testContractAddressesLoaderDeployer(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testForkManagement(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testGetModuleTypes_WhenRegisteredAsMultipleTypes(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testKeyExists(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testRegisterErc20Currency(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testRegisterModule_IfSupportsFollowModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testRegisterModule_IfSupportsPublicationActionModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testRegisterModule_IfSupportsReferenceModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testTestSetup(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  excludeArtifacts(overrides?: CallOverrides): Promise<string[]>;

  excludeContracts(overrides?: CallOverrides): Promise<string[]>;

  excludeSenders(overrides?: CallOverrides): Promise<string[]>;

  failed(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  keyExists(
    json: string,
    key: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setUp(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  targetArtifactSelectors(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

  targetArtifacts(overrides?: CallOverrides): Promise<string[]>;

  targetContracts(overrides?: CallOverrides): Promise<string[]>;

  targetSelectors(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

  targetSenders(overrides?: CallOverrides): Promise<string[]>;

  testArrayHelpers(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testBaseTest(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax(
    moduleType: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotRegisterErc20Currency_Twice(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotRegisterModule_IfModuleDoesNotSupportType(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotRegisterModule_IfModuleTypeIsBiggerThanMax(
    moduleType: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotRegisterModule_IfModuleTypeIsZero(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testCannotRegisterModule_TwiceAsTheSameType(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testContractAddressesLoaderDeployer(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testForkManagement(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testGetModuleTypes_WhenRegisteredAsMultipleTypes(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testKeyExists(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testRegisterErc20Currency(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testRegisterModule_IfSupportsFollowModule(
    module: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testRegisterModule_IfSupportsPublicationActionModule(
    module: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testRegisterModule_IfSupportsReferenceModule(
    module: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testTestSetup(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    excludeArtifacts(overrides?: CallOverrides): Promise<string[]>;

    excludeContracts(overrides?: CallOverrides): Promise<string[]>;

    excludeSenders(overrides?: CallOverrides): Promise<string[]>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    keyExists(
      json: string,
      key: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setUp(overrides?: CallOverrides): Promise<void>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

    targetArtifacts(overrides?: CallOverrides): Promise<string[]>;

    targetContracts(overrides?: CallOverrides): Promise<string[]>;

    targetSelectors(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

    targetSenders(overrides?: CallOverrides): Promise<string[]>;

    testArrayHelpers(overrides?: CallOverrides): Promise<void>;

    testBaseTest(overrides?: CallOverrides): Promise<void>;

    testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax(
      moduleType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotRegisterErc20Currency_Twice(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotRegisterModule_IfModuleDoesNotSupportType(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotRegisterModule_IfModuleTypeIsBiggerThanMax(
      moduleType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotRegisterModule_IfModuleTypeIsZero(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotRegisterModule_TwiceAsTheSameType(
      overrides?: CallOverrides
    ): Promise<void>;

    testContractAddressesLoaderDeployer(
      overrides?: CallOverrides
    ): Promise<void>;

    testForkManagement(overrides?: CallOverrides): Promise<void>;

    testGetModuleTypes_WhenRegisteredAsMultipleTypes(
      overrides?: CallOverrides
    ): Promise<void>;

    testKeyExists(overrides?: CallOverrides): Promise<void>;

    testRegisterErc20Currency(overrides?: CallOverrides): Promise<void>;

    testRegisterModule_IfSupportsFollowModule(
      module: string,
      overrides?: CallOverrides
    ): Promise<void>;

    testRegisterModule_IfSupportsPublicationActionModule(
      module: string,
      overrides?: CallOverrides
    ): Promise<void>;

    testRegisterModule_IfSupportsReferenceModule(
      module: string,
      overrides?: CallOverrides
    ): Promise<void>;

    testTestSetup(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "log(string)"(arg0?: null): logEventFilter;
    log(arg0?: null): logEventFilter;

    "log_address(address)"(arg0?: null): log_addressEventFilter;
    log_address(arg0?: null): log_addressEventFilter;

    "log_array(uint256[])"(val?: null): log_array_uint256_array_EventFilter;
    "log_array(int256[])"(val?: null): log_array_int256_array_EventFilter;
    "log_array(address[])"(val?: null): log_array_address_array_EventFilter;

    "log_bytes(bytes)"(arg0?: null): log_bytesEventFilter;
    log_bytes(arg0?: null): log_bytesEventFilter;

    "log_bytes32(bytes32)"(arg0?: null): log_bytes32EventFilter;
    log_bytes32(arg0?: null): log_bytes32EventFilter;

    "log_int(int256)"(arg0?: null): log_intEventFilter;
    log_int(arg0?: null): log_intEventFilter;

    "log_named_address(string,address)"(
      key?: null,
      val?: null
    ): log_named_addressEventFilter;
    log_named_address(key?: null, val?: null): log_named_addressEventFilter;

    "log_named_array(string,uint256[])"(
      key?: null,
      val?: null
    ): log_named_array_string_uint256_array_EventFilter;
    "log_named_array(string,int256[])"(
      key?: null,
      val?: null
    ): log_named_array_string_int256_array_EventFilter;
    "log_named_array(string,address[])"(
      key?: null,
      val?: null
    ): log_named_array_string_address_array_EventFilter;

    "log_named_bytes(string,bytes)"(
      key?: null,
      val?: null
    ): log_named_bytesEventFilter;
    log_named_bytes(key?: null, val?: null): log_named_bytesEventFilter;

    "log_named_bytes32(string,bytes32)"(
      key?: null,
      val?: null
    ): log_named_bytes32EventFilter;
    log_named_bytes32(key?: null, val?: null): log_named_bytes32EventFilter;

    "log_named_decimal_int(string,int256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;
    log_named_decimal_int(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;

    "log_named_decimal_uint(string,uint256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;
    log_named_decimal_uint(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;

    "log_named_int(string,int256)"(
      key?: null,
      val?: null
    ): log_named_intEventFilter;
    log_named_int(key?: null, val?: null): log_named_intEventFilter;

    "log_named_string(string,string)"(
      key?: null,
      val?: null
    ): log_named_stringEventFilter;
    log_named_string(key?: null, val?: null): log_named_stringEventFilter;

    "log_named_uint(string,uint256)"(
      key?: null,
      val?: null
    ): log_named_uintEventFilter;
    log_named_uint(key?: null, val?: null): log_named_uintEventFilter;

    "log_string(string)"(arg0?: null): log_stringEventFilter;
    log_string(arg0?: null): log_stringEventFilter;

    "log_uint(uint256)"(arg0?: null): log_uintEventFilter;
    log_uint(arg0?: null): log_uintEventFilter;

    "logs(bytes)"(arg0?: null): logsEventFilter;
    logs(arg0?: null): logsEventFilter;
  };

  estimateGas: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<BigNumber>;

    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    excludeArtifacts(overrides?: CallOverrides): Promise<BigNumber>;

    excludeContracts(overrides?: CallOverrides): Promise<BigNumber>;

    excludeSenders(overrides?: CallOverrides): Promise<BigNumber>;

    failed(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    keyExists(
      json: string,
      key: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setUp(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    targetArtifactSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    targetArtifacts(overrides?: CallOverrides): Promise<BigNumber>;

    targetContracts(overrides?: CallOverrides): Promise<BigNumber>;

    targetSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    targetSenders(overrides?: CallOverrides): Promise<BigNumber>;

    testArrayHelpers(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testBaseTest(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax(
      moduleType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotRegisterErc20Currency_Twice(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotRegisterModule_IfModuleDoesNotSupportType(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotRegisterModule_IfModuleTypeIsBiggerThanMax(
      moduleType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotRegisterModule_IfModuleTypeIsZero(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testCannotRegisterModule_TwiceAsTheSameType(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testContractAddressesLoaderDeployer(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testForkManagement(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testGetModuleTypes_WhenRegisteredAsMultipleTypes(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testKeyExists(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testRegisterErc20Currency(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testRegisterModule_IfSupportsFollowModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testRegisterModule_IfSupportsPublicationActionModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testRegisterModule_IfSupportsReferenceModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testTestSetup(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeArtifacts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeSenders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failed(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    keyExists(
      json: string,
      key: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    targetArtifacts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetSelectors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetSenders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testArrayHelpers(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testBaseTest(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotIsModuleRegisteredAs_IfModuleTypeIsBiggerThanMax(
      moduleType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotRegisterErc20Currency_Twice(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotRegisterModule_IfDoesNotSupportDiGiModuleInterface(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotRegisterModule_IfModuleDoesNotSupportType(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotRegisterModule_IfModuleTypeIsBiggerThanMax(
      moduleType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotRegisterModule_IfModuleTypeIsZero(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testCannotRegisterModule_TwiceAsTheSameType(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testContractAddressesLoaderDeployer(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testForkManagement(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testGetModuleTypes_WhenRegisteredAsMultipleTypes(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testKeyExists(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testRegisterErc20Currency(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testRegisterModule_IfSupportsFollowModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testRegisterModule_IfSupportsPublicationActionModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testRegisterModule_IfSupportsReferenceModule(
      module: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testTestSetup(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
