/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Events } from "./Events";
export type { HandlesEvents } from "./HandlesEvents";
export type { RegistryEvents } from "./RegistryEvents";
export type { TestEvents } from "./TestEvents";
